Repository ovh/public-cloud-examples, pull requests merged in 2024-07, with the labels that each got.

#61 [NEW] - add Audio Summarizer Assistant tutorial for AI Endpoints
  ai/ai-endpoints/README.md
  ai/ai-endpoints/audio-summarizer-assistant/README.md
  ai/ai-endpoints/audio-summarizer-assistant/audio-summarizer-app.py
  ai/ai-endpoints/audio-summarizer-assistant/audio-summarizer-web-app.png
  ai/ai-endpoints/audio-summarizer-assistant/requirements.txt
Labels: 🧠 AI

#62 feat: ✨ Java langchain4j raw chatbot
  .gitignore
  ai/ai-endpoints/README.md
  ai/ai-endpoints/java-langchain4j-chatbot/README.md
  ai/ai-endpoints/java-langchain4j-chatbot/pom.xml
  ai/ai-endpoints/java-langchain4j-chatbot/src/main/java/com/ovhcloud/examples/aiendpoints/BlockingChatbot.java
  ai/ai-endpoints/java-langchain4j-chatbot/src/main/java/com/ovhcloud/examples/aiendpoints/MemoryStreamingChatbot.java
  ai/ai-endpoints/java-langchain4j-chatbot/src/main/java/com/ovhcloud/examples/aiendpoints/RAGStreamingChatbot.java
  ai/ai-endpoints/java-langchain4j-chatbot/src/main/java/com/ovhcloud/examples/aiendpoints/StreamingChatbot.java
  ai/ai-endpoints/java-langchain4j-chatbot/src/main/resources/logback.xml
  ai/ai-endpoints/java-langchain4j-chatbot/src/main/resources/rag-files/content.txt
Labels: ✨ New demos ✨, 🧠 AI

#65 feat: Create a kubernetes cluster in a Local Zone through rancher
  containers-orchestration/managed-rancher/create-k8s-lz-instances/README.md
  containers-orchestration/managed-rancher/create-k8s-lz-instances/custom.png
  containers-orchestration/managed-rancher/create-k8s-lz-instances/etcdnode.png
  containers-orchestration/managed-rancher/create-k8s-lz-instances/k3s.png
  containers-orchestration/managed-rancher/create-k8s-lz-instances/lz.png
  containers-orchestration/managed-rancher/create-k8s-lz-instances/search.png
  containers-orchestration/managed-rancher/create-k8s-lz-instances/workernode.png
Labels: 🏗️ MKS / MRS / Rancher, ✨ New demos ✨
