Repository ovh/public-cloud-examples, pull requests merged in 2024-06, with the labels that each got.

#55 doc: 📝 add README file to AI endpoints demos
  ai/ai-endpoints/README.md
Labels: documentation

#60 add basics python kafka example
  .gitignore
  databases-analytics/databases/kafka-basics/README.md
  databases-analytics/databases/kafka-basics/python/consumer.py
  databases-analytics/databases/kafka-basics/python/producer.py
  databases-analytics/databases/kafka-basics/python/readme.md
  databases-analytics/databases/kafka-basics/python/requirements.txt
  databases-analytics/databases/kafka-basics/python/sslcerts/copy here your certificates
Labels: enhancement, 💿 DBaaS

#59 feat: ✨ V1 for RAG + AI Endpoints + LangChain + Python
  ai/ai-endpoints/python-langchain-chatbot/README.md
  ai/ai-endpoints/python-langchain-chatbot/chat-bot-streaming-rag.py
  ai/ai-endpoints/python-langchain-chatbot/rag-files/content.txt
  ai/ai-endpoints/python-langchain-chatbot/requirements.txt
Labels: ✨ New demos ✨, 🧠 AI
