Repository ovh/public-cloud-examples, pull requests merged in 2024-03, with the labels that each got.

#38 feat: 💿 PostgreSQL with TF
  databases-analytics/databases/.gitkeep
  databases-analytics/databases/postgresql-tf/README.md
  databases-analytics/databases/postgresql-tf/my-ovh_postgresql_db.tf
  databases-analytics/databases/postgresql-tf/my-provider.tf
  databases-analytics/databases/postgresql-tf/my-variables.tf
  databases-analytics/databases/postgresql-tf/output.tf
Labels: 🏗️ Terraform, 💿 DBaaS

#40 feat: ✨ Mks autoscaler demo
  containers-orchestration/managed-kubernetes/autoscaler/.dockerignore
  containers-orchestration/managed-kubernetes/autoscaler/Dockerfile
  containers-orchestration/managed-kubernetes/autoscaler/README.md
  containers-orchestration/managed-kubernetes/autoscaler/cpu-load.py
  containers-orchestration/managed-kubernetes/autoscaler/cpu-load.yml
Labels: 🏗️ MKS

#43 feat: Create a MKS through CDK for Terraform in Go
  .gitignore
  containers-orchestration/managed-kubernetes/create-cluster-with-cdktf-and-go/README.md
  containers-orchestration/managed-kubernetes/create-cluster-with-cdktf-and-go/cdktf.json
  containers-orchestration/managed-kubernetes/create-cluster-with-cdktf-and-go/go.mod
  containers-orchestration/managed-kubernetes/create-cluster-with-cdktf-and-go/go.sum
  containers-orchestration/managed-kubernetes/create-cluster-with-cdktf-and-go/main.go
Labels: 🏗️ MKS / MRS / Rancher, ✨ New demos ✨

#47 feat: Add rancher examples: create a MKS and import an existing Kubernetes cluster
  containers-orchestration/managed-rancher/create-mks/README.md
  containers-orchestration/managed-rancher/import-kubernetes-cluster/README.md
Labels: 🏗️ MKS / MRS / Rancher, ✨ New demos ✨
